# Generated by Django 5.2.9 on 2025-12-20 10:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("500.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="recipient_id",
            field=models.CharField(
                db_index=True, default=0, editable=False, max_length=10, unique=True
            ),
            preserve_default=False,
        ),
    ]
