# Generated by Django 5.2.9 on 2025-12-20 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="from_account",
        ),
        migrations.RemoveField(
            model_name="balance",
            name="account",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="to_account",
        ),
        migrations.RemoveField(
            model_name="balance",
            name="transaction",
        ),
        migrations.AddField(
            model_name="transaction",
            name="from_recipient_id",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="from_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sent_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="to_recipient_id",
            field=models.CharField(default="0000000000", max_length=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="to_user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Account",
        ),
        migrations.DeleteModel(
            name="Balance",
        ),
    ]
