# Generated by Django 5.2.9 on 2025-12-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("transaction_created", "Transaction Created"),
                            ("transaction_completed", "Transaction Completed"),
                            ("transaction_failed", "Transaction Failed"),
                            ("balance_updated", "Balance Updated"),
                            ("user_login", "User Login"),
                            ("user_logout", "User Logout"),
                            ("account_created", "Account Created"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("data", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_immutable", models.BooleanField(default=True, editable=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
